#!/bin/sh -e

case "$1" in
    configure)
	if ! getent passwd rbldns >/dev/null; then
		adduser --system --group --home /var/lib/rbldns --no-create-home rbldns
		mkdir -p -m0755 /var/lib/rbldns
	fi
    ;;
esac

#DEBHELPER#

